# Generated by Django 5.2.17 on 2026-09-21 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_review_name_review_created_at_review_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='icon',
            field=models.ImageField(blank=True, upload_to='icons/'),
        ),
    ]
